package com.example.pdfpay.controller;

import com.example.pdfpay.entity.*; import com.example.pdfpay.repository.*; import com.example.pdfpay.service.LocalWordFilter; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*; import java.util.concurrent.*;

@RestController @RequestMapping("/api/community")
public class CommunityController {
 private final ForumPostRepository posts; private final ForumCommentRepository comments; private final ForumVoteRepository votes; private final ForumReportRepository reports; private final UserAccountRepository users; private final LocalWordFilter filter;
 private final ConcurrentHashMap<String,Long> limits=new ConcurrentHashMap<>();
 public CommunityController(ForumPostRepository p,ForumCommentRepository c,ForumVoteRepository v,ForumReportRepository r,UserAccountRepository u,LocalWordFilter f){posts=p;comments=c;votes=v;reports=r;users=u;filter=f;}
 public record PostRequest(String title,String body,String tags){} public record CommentRequest(String body){} public record ReportRequest(String reason){}
 @GetMapping("/posts") public List<Map<String,Object>> list(@RequestParam(required=false) String q,@RequestParam(required=false) String tag){ return posts.findTop100ByHiddenFalseOrderByCreatedAtDesc().stream().filter(p->matches(p,q,tag)).sorted(Comparator.comparingDouble(this::score).reversed()).map(p->postMap(p,null)).toList(); }
 @GetMapping("/trending") public List<Map<String,Object>> trending(){return posts.findTop100ByHiddenFalseOrderByCreatedAtDesc().stream().sorted(Comparator.comparingDouble(this::score).reversed()).limit(10).map(p->postMap(p,null)).toList();}
 @GetMapping("/posts/{id}") public ResponseEntity<?> get(@PathVariable Long id,Authentication a){return posts.findById(id).map(p->{var m=postMap(p,a);m.put("comments",comments.findByPostIdAndHiddenFalseOrderByCreatedAtAsc(id).stream().map(c->commentMap(c,a)).toList());return ResponseEntity.ok(m);}).orElseGet(()->ResponseEntity.notFound().build());}
 @PostMapping("/posts") public ResponseEntity<?> create(@RequestBody PostRequest r,Authentication a){if(!allowed(a,"post"))return tooFast();if(blank(r.title())||blank(r.body()))return bad("Title and question are required.");if(r.title().length()>140||r.body().length()>5000)return bad("Question is too long.");if(filter.containsBlockedWords(r.title())||filter.containsBlockedWords(r.body()))return bad("Please remove inappropriate language or obfuscated profanity from your question."); UserAccount u=user(a);ForumPost p=new ForumPost();p.setAuthor(u);p.setTitle(r.title().trim());p.setBody(r.body().trim());p.setTags(cleanTags(r.tags()));p.setCreatedAt(Instant.now());p.setHidden(false);return ResponseEntity.status(HttpStatus.CREATED).body(postMap(posts.save(p),a));}
 @PostMapping("/posts/{id}/comments") public ResponseEntity<?> comment(@PathVariable Long id,@RequestBody CommentRequest r,Authentication a){if(!allowed(a,"comment"))return tooFast();if(blank(r.body()))return bad("Answer cannot be empty.");if(r.body().length()>3000)return bad("Answer is too long.");if(filter.containsBlockedWords(r.body()))return bad("Please remove inappropriate language or obfuscated profanity from your answer.");return posts.findById(id).map(p->{if(p.isHidden())return ResponseEntity.status(HttpStatus.NOT_FOUND).body(Map.of("error","Question not found."));ForumComment c=new ForumComment();c.setPost(p);c.setAuthor(user(a));c.setBody(r.body().trim());c.setCreatedAt(Instant.now());return ResponseEntity.status(HttpStatus.CREATED).body(commentMap(comments.save(c),a));}).orElseGet(()->ResponseEntity.notFound().build());}
 @PostMapping("/posts/{id}/vote") public ResponseEntity<?> vote(@PathVariable Long id,Authentication a){return posts.findById(id).map(p->{UserAccount u=user(a);if(votes.existsByUserIdAndPostId(u.getId(),id))votes.deleteByUserIdAndPostId(u.getId(),id);else{ForumVote v=new ForumVote();v.setUser(u);v.setPost(p);v.setCreatedAt(Instant.now());votes.save(v);}return ResponseEntity.ok(Map.of("upvotes",votes.countByPostId(id),"voted",votes.existsByUserIdAndPostId(u.getId(),id)));}).orElseGet(()->ResponseEntity.notFound().build());}
 @PostMapping("/posts/{id}/accept/{commentId}") public ResponseEntity<?> accept(@PathVariable Long id,@PathVariable Long commentId,Authentication a){return posts.findById(id).map(p->{if(!p.getAuthor().getId().equals(user(a).getId()))return ResponseEntity.status(403).body(Map.of("error","Only the question author can accept an answer."));return comments.findById(commentId).map(c->{if(!c.getPost().getId().equals(id))return ResponseEntity.badRequest().body(Map.of("error","Answer does not belong to this question."));p.setAcceptedComment(c);posts.save(p);return ResponseEntity.ok(Map.of("acceptedCommentId",commentId));}).orElseGet(()->ResponseEntity.notFound().build());}).orElseGet(()->ResponseEntity.notFound().build());}
 @PostMapping("/posts/{id}/report") public ResponseEntity<?> reportPost(@PathVariable Long id,@RequestBody ReportRequest r,Authentication a){return posts.findById(id).map(p->{ForumReport x=new ForumReport();x.setReporter(user(a));x.setPost(p);x.setReason(filter.cleanForStorage(r.reason(),500));x.setCreatedAt(Instant.now());reports.save(x);return ResponseEntity.ok(Map.of("message","Thanks. The report was sent to moderators."));}).orElseGet(()->ResponseEntity.notFound().build());}
 @PostMapping("/comments/{id}/report") public ResponseEntity<?> reportComment(@PathVariable Long id,@RequestBody ReportRequest r,Authentication a){return comments.findById(id).map(c->{ForumReport x=new ForumReport();x.setReporter(user(a));x.setComment(c);x.setReason(filter.cleanForStorage(r.reason(),500));x.setCreatedAt(Instant.now());reports.save(x);return ResponseEntity.ok(Map.of("message","Thanks. The report was sent to moderators."));}).orElseGet(()->ResponseEntity.notFound().build());}
 @GetMapping("/users/{id}") public ResponseEntity<?> profile(@PathVariable Long id){return users.findById(id).map(u->Map.of("id",u.getId(),"name",u.getDisplayName(),"createdAt",u.getCreatedAt(),"questions",posts.countByAuthorIdAndHiddenFalse(id),"answers",comments.countByAuthorIdAndHiddenFalse(id),"upvotes",posts.findTop100ByHiddenFalseOrderByCreatedAtDesc().stream().filter(p->p.getAuthor().getId().equals(id)).mapToLong(p->votes.countByPostId(p.getId())).sum())).map(ResponseEntity::ok).orElseGet(()->ResponseEntity.notFound().build());}
 private boolean matches(ForumPost p,String q,String tag){boolean qm=blank(q)||((p.getTitle()+" "+p.getBody()).toLowerCase(Locale.ROOT).contains(q.toLowerCase(Locale.ROOT)));boolean tm=blank(tag)||Arrays.asList(Optional.ofNullable(p.getTags()).orElse("").split(",")).stream().anyMatch(x->x.trim().equalsIgnoreCase(tag));return qm&&tm;}
 private double score(ForumPost p){long v=votes.countByPostId(p.getId()),c=comments.findByPostIdAndHiddenFalseOrderByCreatedAtAsc(p.getId()).size();long hours=Math.max(1,Duration.between(p.getCreatedAt(),Instant.now()).toHours());return v*4+c*2+Math.max(0,72-hours)/12.0;}
 private Map<String,Object> postMap(ForumPost p,Authentication a){Map<String,Object>m=new LinkedHashMap<>();m.put("id",p.getId());m.put("title",p.getTitle());m.put("body",p.getBody());m.put("author",p.getAuthor().getDisplayName());m.put("authorId",p.getAuthor().getId());m.put("createdAt",p.getCreatedAt());m.put("tags",Optional.ofNullable(p.getTags()).orElse(""));m.put("commentCount",comments.findByPostIdAndHiddenFalseOrderByCreatedAtAsc(p.getId()).size());m.put("upvotes",votes.countByPostId(p.getId()));m.put("voted",a!=null&&votes.existsByUserIdAndPostId(user(a).getId(),p.getId()));m.put("acceptedCommentId",p.getAcceptedComment()==null?null:p.getAcceptedComment().getId());return m;}
 private Map<String,Object> commentMap(ForumComment c,Authentication a){Map<String,Object>m=new LinkedHashMap<>();m.put("id",c.getId());m.put("body",c.getBody());m.put("author",c.getAuthor().getDisplayName());m.put("authorId",c.getAuthor().getId());m.put("createdAt",c.getCreatedAt());return m;}
 private UserAccount user(Authentication a){String email=a.getName();if(a instanceof org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken t){Object v=t.getPrincipal().getAttribute("email");if(v!=null)email=v.toString();}return users.findByEmailIgnoreCase(email).orElseThrow();}
 private String cleanTags(String x){if(x==null)return "";return Arrays.stream(x.split(",")).map(String::trim).filter(t->t.matches("[A-Za-z0-9+# .-]{1,30}")).distinct().limit(5).reduce((a,b)->a+","+b).orElse("");}
 private boolean blank(String s){return s==null||s.trim().isEmpty();} private ResponseEntity<?> bad(String s){return ResponseEntity.badRequest().body(Map.of("error",s));} private ResponseEntity<?> tooFast(){return ResponseEntity.status(429).body(Map.of("error","You're posting too quickly. Please wait a moment and try again."));}
 private boolean allowed(Authentication a,String action){String k=a.getName()+":"+action;long now=System.currentTimeMillis();Long old=limits.putIfAbsent(k,now);if(old==null)return true;if(now-old<20_000)return false;limits.put(k,now);return true;}
}
